version: "3"
services:
  mongo:
    container_name: mongo_container
    image: mongo:5.0.10
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    ports:
      - "5050:5050"
      - "9222:9222"
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/app/dist
    depends_on:
      - mongo

